name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compile
      run: gcc test_tabuleiro-ox.c -o test_tabuleiro-ox
    - name: execute
      run: ./test_tabuleiro-ox
    - name: compile programa principal
      run: gcc tabuleiro-ox.c -o tabuleiro-ox
    - name: execute programa principal
      run: ./tabuleiro-ox O X O X X X O O X

